accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
# from django.contrib.auth import views as auth_views

from accounts import views
from accounts.views import Home, Registers, Dashboard, logout, CompanyActivate, Activated, SuccessMessage, \
    ResetPasswordRequestView, PasswordResetConfirmView

urlpatterns = [
    url(r'^test/$', views.index, name='home'),
    url(r'^$', Home.as_view(), name='home'),
    url(r'register/$', Registers.as_view(), name='register'),
    url(r'activate/$', Activated.as_view(), name='activateaccount'),
    url(r'companyactivate/(?P<token>[\w-]+)$', CompanyActivate.as_view(), name='companyactivate'),
    url(r'clientdashboard/$', login_required(Dashboard.as_view()), name='dashboard'),
    url(r'registration-success/$', SuccessMessage.as_view(), name='registersuccess'),
    url(r'signin/$', views.login, name='login'),
    url(r'^logout/$', logout, {"next_page": '/'}, name="logout"),
    url(r'^reset_password', ResetPasswordRequestView.as_view(), name="reset_password"),
    url(r'^account/reset_password_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(),
        name='confirmpaass'),

    # url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    # url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    # url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #     auth_views.password_reset_confirm, name='password_reset_confirm'),
    # url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    # url(r'^accounts/activate/(?P<activation_key>\w+)/$',
    #     Home.as_view(),
    #     {'backend': 'registration.backends.default.DefaultBackend'},
    #     name='registration_activate'),
]

hire/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from hire.views import HireView, FreelancerHireView, MilestoneListView

urlpatterns = [

    url(r'hire/(?P<slug>[-\w]+)/$', login_required(HireView.as_view()), name='hireviews'),
    url(r'hires/(?P<slug>[-\w]+)/$', login_required(FreelancerHireView.as_view()), name='hireviewsfreelancer'),
    url(r'listing-milestones$', login_required(MilestoneListView.as_view()), name='listmilestone'),

]

newproject/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin



import accounts
from newproject import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('accounts.urls')),
    url(r'^freelancer/', include('freelancer.urls')),
    url(r'^client/', include('client.urls')),
    url(r'^freelancer-company/', include('freelancer_company.urls')),
    url(r'^client-company/', include('client_company.urls')),
    url(r'^site_administration/', include('site_administration.urls',namespace='siteadmin')),

    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^hire/', include('hire.urls')),
    url(r'^notifications/', include('notifications.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += i18n_patterns(
    url(r'^', include('accounts.urls', namespace='index')),
    url(r'^polls/', include('accounts.urls', namespace='login')),
    url(r'^', include('freelancer.urls', namespace='freelancer')),
    url(r'^', include('client.urls', namespace='client')),
    url(r'^', include('hire.urls', namespace='hire')),
    url(r'^', include('freelancer_company.urls', namespace='freelancer-company')),
    url(r'^', include('client_company.urls', namespace='client-company')),
    url(r'^', include('notifications.urls', namespace='notifications')),
    url(r'^accounts/', include('registration.backends.hmac.urls'))
)

handler404 = accounts.views.error_404
handler500 = accounts.views.error_500

accounts/views.py
import StringIO
import email
import json

import logging
import threading
from urlparse import urlparse

import datetime

from PIL import Image
from django.contrib import messages
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import deprecate_current_app
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ValidationError
from django.core.files.base import ContentFile
from django.core.mail import send_mail
from django.core.validators import validate_email
from django.db.models.query_utils import Q
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render, render_to_response, redirect, resolve_url
from django.template import Context
from django.template import RequestContext
from django.template import Template
from django.template import loader
from django.template.loader import render_to_string
from django.template.response import TemplateResponse
from django.utils.crypto import get_random_string
from django.utils.encoding import force_bytes
from django.utils.http import is_safe_url, urlsafe_base64_encode, urlsafe_base64_decode
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from rolepermissions.decorators import has_role_decorator
from registration.backends.hmac.views import RegistrationView
from django.contrib.auth import (
    REDIRECT_FIELD_NAME, get_user_model, login as auth_login,
    logout as auth_logout, update_session_auth_hash, )
# Create your views here.
from accounts.forms import RegisterForm, LoginForm, ActivationForm, PasswordResetRequestForm, SetPasswordForm
from accounts.models import Users, User_Type
from client.mixins import ClientMixin
from client.models import Client_Profile, ClientJobs, PaymentType, Duration, JobStatus, ApplyJob
from freelancer.mixins import MainMixin
from freelancer.models import WorkCategories, WorkSubCategories, Skills, Freelancer_Profile, HourlyRate, LocationDetails, \
    EmploymentHistory, Certifications, FreelancerPortfolio
from hire.models import ContractStatus, JobsMilestone, MileStoneStatus, TimeWork, TimesheetStatus
from hire.models import HiredJobsContract
from newproject import settings
from newproject.settings import DEFAULT_FROM_EMAIL

logger = logging.getLogger(__name__)
from rolepermissions.roles import assign_role
from rolepermissions.roles import remove_role

from rolepermissions.mixins import HasPermissionsMixin
from rolepermissions.roles import get_user_roles
from django.core.cache import cache
import requests
from cities_light.models import Country, Region, City



def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")
def next_weekday(d, weekday):
    days_ahead = weekday - d.weekday()
    # if days_ahead <= 0: # Target day already happened this week
    #     days_ahead += 7
    return d + datetime.timedelta(days_ahead)



class Home(MainMixin,TemplateView):
    template_name = "accounts/home.html"
    def next_weekday(d, weekday):
        days_ahead = weekday - d.weekday()
        # if days_ahead <= 0: # Target day already happened this week
        #     days_ahead += 7
        return d + datetime.timedelta(days_ahead)

    def get(self, request, *args, **kwargs):
        template_name = "accounts/home.html"
        users =self.get_users_list('0')
        online =self.get_users_list('1')
        jobs =self.get_jobs_list()
        print users.count(),"hjhjh"
        context = {'online': online.count(),'jobs':jobs.count(),'users':users.count(),'key_words_search':self.get_all_freelancer()}

        redirect_field_name = REDIRECT_FIELD_NAME,
        # workcategory = requests.get("http://52.15.241.137/atlancer_wp/api/?func=getWorkCategory").json()
        #
        # for work in workcategory:
        #
        #     workcategory, workcategorys = WorkCategories.objects.get_or_create(category_title= work['category_title'])
        #     workcategory.save()
        # worksubcategoryss = requests.get("http://52.15.241.137/atlancer_wp/api/?func=getWorkSubCategory").json()
        #
        # for sub in worksubcategoryss:
        #     workcategory =WorkCategories.objects.get(category_title=sub['category_title'])
        #     worksubcategory, worksubcategorys = WorkSubCategories.objects.get_or_create(sub_category_title=sub['sub_category_title'],work_category=workcategory)
        #     worksubcategory.save()
        #
        # workskills = requests.get("http://52.15.241.137/atlancer_wp/api/?func=getSkills").json()
        #
        # for skills in workskills:
        #     category =WorkCategories.objects.get(category_title=skills['category_title'])
        #     # print category,"jnmjjjjjjjjjjjjjjj"
        #     skillsobject, skillsss = Skills.objects.get_or_create(name=skills['skills'])
        #     skillsobject.category.add(category)
        #     skillsobject.save()
        # responsess = requests.get("http://52.15.241.137/atlancer_wp/api/?func=getUsers").json()
        #
        # for res in responsess:
        #     print res['user_type'], "typrtypr"
        #     # print res['created_date'],"ddd"
        #     if res['user_type'] == '1':
        #         type ="FREELANCER"
        #     else:
        #         type ="CLIENT"
        #     user_type = User_Type.objects.get(type=type)
        #     # print user_type, "typrtypr"
        #     invite_type = User_Type.objects.get(type='OWNER')
        #     store_corporate,store_corporates=Users.objects.get_or_create(email=res['email'])
        #     if store_corporates:
        #         store_corporate.token=get_random_string(length=32)
        #         store_corporate.first_name=res['first_name']
        #         store_corporate.last_name=res['last_name']
        #         store_corporate.active_account=user_type
        #         store_corporate.user_type=user_type
        #         store_corporate.invite_type=invite_type
        #         store_corporate.set_password('A!sgiwyGek#269')
        #         store_corporate.save()
        #     user = Users.objects.get(email=res['email'])
        #     if res['user_type'] == '1':
        #       url = "http://52.15.241.137/atlancer_wp/api?func=getFreelancerProfile&email="+res['email']
        #       # print url
        #       details = requests.get(url).json()
        #
        #
        #       user = Users.objects.get(email=res['email'])
        #       profile, profiles = Freelancer_Profile.objects.get_or_create(user=user)
        #       profile.title = details['title']
        #       if details['profile']:
        #           path = details['profile']
        #           domain, paths = split_url(path)
        #           filename = get_url_tail(paths)
        #           fobject = retrieve_image(path)
        #           pil_image = Image.open(fobject)
        #           django_file = pil_to_django(pil_image)
        #           profile.profile.save(filename, django_file)
        #
        #       profile.about = details['about']
        #       if details['categoryname'] :
        #           workcategory = WorkCategories.objects.get(category_title=details['categoryname'])
        #           profile.workcategory = workcategory
        #       profile.save()
        #       if details['skills'] :
        #           self.delete_existing_skill(user)
        #
        #
        #           for skills in Skills.objects.filter(name__in=[details['skills']],category=workcategory):
        #
        #               profile.skills.add(skills)
        #               profile.save()
        #       if details['subcategory'] :
        #           print details['subcategory'], "sdddddddd"
        #           print WorkSubCategories.objects.filter(sub_category_title__in=[details['subcategory']],work_category=workcategory), "sdddddddd"
        #           self.delete_existing_subcategory(user)
        #
        #           for subcategorys in WorkSubCategories.objects.filter(sub_category_title__in=[details['subcategory']],work_category=workcategory):
        #               print subcategorys,"dd"
        #               profile.subcategory.add(subcategorys)
        #               profile.save()
        #       url = "http://52.15.241.137/atlancer_wp/api?func=getHourlyrate&email=" + res['email']
        #
        #       details = requests.get(url).json()
        #       if details['hourly_rate']:
        #           hourly, hourlys = HourlyRate.objects.get_or_create(user=user)
        #           hourly.hourly_rate=details['hourly_rate']
        #           hourly.actual_rate=details['actual_rate']
        #           hourly.save()
        #       url = "http://52.15.241.137/atlancer_wp/api?func=getLocation&email=" + res['email']
        #
        #       details = requests.get(url).json()
        #       if details['address'] or details['country'] or details['zip_code']:
        #           location, locations = LocationDetails.objects.get_or_create(user=user)
        #           if details['country'] :
        #               location.country = Country.objects.get(name=details['country'])
        #           if details['state']:
        #               location.state = Region.objects.get(name=details['state'],country__name=details['country'])
        #           if details['city']:
        #               print details['city'],"details['city']details['city']details['city']"
        #               try:
        #                  location.city = City.objects.get(name=details['city'],region__name=details['state'])

templates/accounts/dashboard.html
<p>Logged in {{request.user.user_type}}</p>

<a href="{% url 'logout' %}">Logout</a>

templates/accounts/login.html
{% extends 'base.html' %}
{% block extra_html %}
<div class="search-strip">
          <div class="container">
            <div class="top-search-form">
              <input type="text" id="search-box" value="search freelancers" placeholder="" />
              <ul class="search-dropdown">
                <li class="search-freelancers">search freelancers</li>
                <li class="search-freelancers">search Jobs</li>
              </ul>
              <div class="search-buttons-cover">
              <span class="search-drop-button"></span>
             <input type="button" value="search">
            </div>
            </div>
          </div>
      </div>
{% endblock %}

{% load staticfiles%}
{% block content %}
{% block style %}

     <!--fonts cdns-->
    <link href="https://fonts.googleapis.com/css?family=Rubik:100,300,400,500,700,900|Sintony:400,700" rel="stylesheet">



{% endblock %}


<!--login form-->
    <section class="login-cover full-strip" id="login-cover">
      <div class="login-form-cover">
          <div class="form-cover">
          <!--<div class="status-message failed" {% if form.non_field_errors %} style="display:block;"{% endif%} >-->
      <!--<p id="messageStatus">{{ form.non_field_errors }} </p>-->
      <!--<a href="#" onclick="HideDisplayMessage()" class="close"></a>-->
    <!--</div>-->

          <h2 class="form-title">Log in and get to work</h2>
          <p class="form-description"> It's the simplest and safest way to get work done online.  </p>

          <form role="form" novalidate action="." method="post">

              {% csrf_token %}
              <!--{{form}}-->
              <div class="field-row">

                     {{form.username}}
                  <!--<input type="text" name="email" placeholder="Email"  />-->
                  {{form.username.errors}}
                  {{ form.non_field_errors }}
              </div>
              <div class="field-row">
                  {{form.password}}
                  <!--<input type="password" name="password" placeholder="Password"  />-->
                  {{form.password.errors}}
              </div>
              <div class="field-row">
                  <div class="grid-50">
                      <label class="checkbox inline-cover">
                          <input name="rememberme"  class="toggle" type="checkbox">
                          <span>Remember me</span>
                      </label>


                  </div>
                  <div class="grid-50">
                    <label class="text-right pull-right"><a href="{% url 'index:reset_password' %}" class="forgot-password">Forgot password?</a></label>
                  </div>
              </div>
              <button type="submit" class="light-blue-border-button">Log In</button>
              <!--<input type="submit">-->
            </form>
            <p> Don't have an account?  <a href="{% url 'index:register' %}" class="sign-up-link"> SIGN UP </a> </p>
      </div>
        </div>
    </section>
    <!--login form ends here-->
 {% endblock %}

templates/accounts/registration.html
{% extends 'base.html' %}
{% load staticfiles%}
{% block style %}

     <!--fonts cdns-->
<style>
		.loader-input {
		  border: 2px solid #f3f3f3;
		  border-radius: 50%;
		  border-top: 2px solid #107bc7;
		  border-right: 2px solid #107bc7;
		  border-bottom: 2px solid #cccccc;
		  border-left: 2px solid #cccccc;
		  width: 17px;
		  height: 17px;
		  position: absolute;
		  top: 10px;
		  right: 10px;
		  -webkit-animation: spin 0.5s linear infinite;
		  animation: spin 0.5s linear infinite;
		  display: none;
		}
		.has-input-loader{
		    position: relative;
		}
		.has-input-loader .loader-input{
			display: block;

		}
		.has-loader.has-input-loader .loader-input{
			top: 12px;
			right: 50%;
			margin-right: -10px;
			z-index: 3;
		}
		.loader {
		  border: 3px solid #f3f3f3;
		  border-radius: 50%;
		  border-top: 3px solid #5cbc63;
		  border-bottom: 3px solid #5cbc63;
		  width: 31px;
		  height: 31px;
		  margin: 0 auto;
		  -webkit-animation: spin 2s linear infinite;
		  animation: spin 2s linear infinite;
		  margin-bottom: 5px;
		}

		.block_overflow{
			overflow: hidden;
		}
        .loading-pulse-bg{
            position: absolute;
            top: 0;
            right: 0;
            bottom: 0;
            left: 0;
            background: rgba(255,255,255, 0.85);
        }
		@-webkit-keyframes spin {
		  0% { -webkit-transform: rotate(0deg); }
		  100% { -webkit-transform: rotate(360deg); }
		}

		@keyframes spin {
		  0% { transform: rotate(0deg); }
		  100% { transform: rotate(360deg); }
		}
		.main-box.hide-x{
			overflow-x: hidden !important;
		}
		@keyframes spinner-loader {
  0% {
    -moz-transform: rotate(0deg);
    -ms-transform: rotate(0deg);
    -webkit-transform: rotate(0deg);
    transform: rotate(0deg);
  }
  100% {
    -moz-transform: rotate(360deg);
    -ms-transform: rotate(360deg);
    -webkit-transform: rotate(360deg);
    transform: rotate(360deg);
  }
}
/* :not(:required) hides this rule from IE9 and below */
.spinner-loader:not(:required) {
  -moz-animation: spinner-loader 1500ms infinite linear;
  -webkit-animation: spinner-loader 1500ms infinite linear;
  animation: spinner-loader 1500ms infinite linear;
  -moz-border-radius: 0.5em;
  -webkit-border-radius: 0.5em;
  position: absolute;
  left: 50%;
  top: 18px;

  z-index: 2;
  border-radius: 50%;
  box-shadow: rgba(0, 0, 51, 0.05) 1.0em 0 0 0, rgba(0, 0, 51, 0.1) 0.71em 0.71em 0 0, rgba(0, 0, 51, 0.2) 0 1.0em 0 0, rgba(0, 0, 51, 0.3) -0.71em 0.71em 0 0, rgba(0, 0, 51, 0.35) -1.0em 0 0 0, rgba(0, 0, 51, 0.4) -0.71em -0.71em 0 0, rgba(0, 0, 51, 0.45) 0 -1.0em 0 0, rgba(0, 0, 51, 0.5) 0.71em -0.71em 0 0;
  display: inline-block;
  font-size: 10px;
  width: 0.5em;
  height: 0.5em;
  margin-left: -3px;
  overflow: hidden;
  text-indent: 100%;
}
		</style>
    <link href="https://fonts.googleapis.com/css?family=Rubik:100,300,400,500,700,900|Sintony:400,700" rel="stylesheet">



{% endblock %}

{% block extra_html %}
<div class="search-strip">
          <div class="container">
            <div class="top-search-form">
              <input type="text" id="search-box" value="search freelancers" placeholder="" />
              <ul class="search-dropdown">
                <li class="search-freelancers">search freelancers</li>
                <li class="search-freelancers">search Jobs</li>
              </ul>
              <div class="search-buttons-cover">
              <span class="search-drop-button"></span>
             <input type="button" value="search">
            </div>
            </div>
          </div>
      </div>
{% endblock %}
{% block content %}

    <!--lregister n form-->
    <section class="register-cover full-strip" id="register-cover">
      <div class="register-form-cover">
          <div class="form-cover">
           <div class="status-message ">
            <p id="messageStatus">Success Message will goes here </p>
            <a href="#" onclick="HideDisplayMessage()" class="close"></a>
         </div>
          <h2 class="form-title">Hire and Find Freelance Jobs Online </h2>
          <p class="form-description">It is a place for employers and freelancer to connect, <br />
collaborate and get work done.</p>

          <form method ='post' novalidate action="." id="registration">
              <div id="success"></div>
              {% csrf_token %}
              <div class="field-row">

                <div class="grid-50  padding-right-5">
                  <!--<input type="text" placeholder="First Name"  name="first_name"/>-->
                    {{form.first_name}}
                    <span class="errors_first_name error"></span>
                </div>
                <div class="grid-50 padding-left-5">
                  <!--<input type="text"  placeholder="Last Name"   name="last_name"/>-->
                    {{form.last_name}}
                    <span class="errors_last_name error"></span>
                </div>
              </div>

              <div class="field-row">
                <div class="grid-50 padding-right-5">
                  <!--<input type="password"  placeholder="Password" name="password" />-->
                    {{form.password1}}
                     <span class="errors_password1  error"></span>
                </div>
                <div class="grid-50 padding-left-5">
                  <!--<input type="password"  name="password2"   placeholder="Confirm Password" />-->
                      {{form.password2}}
                     <span class="errors_password2 error"></span>
                </div>
              </div>

              <!--<div class="field-row">-->
                <!--<div class="grid-50 padding-right-5">-->
                <!--&lt;!&ndash;<select name="country" >&ndash;&gt;-->
                  <!--&lt;!&ndash;<option value="Afghanistan">Select Coutry</option>&ndash;&gt;-->
                  <!--&lt;!&ndash;<option value="Albania">Albania</option>&ndash;&gt;-->
                  <!--&lt;!&ndash;<option value="Algeria">Algeria</option>&ndash;&gt;-->
                  <!--&lt;!&ndash;<option value="American Samoa">American Samoa</option>&ndash;&gt;-->
                  <!--&lt;!&ndash;<option value="Andorra">Andorra</option>&ndash;&gt;-->
                  <!--&lt;!&ndash;<option value="Angola">Angola</option>&ndash;&gt;-->
                  <!--&lt;!&ndash;<option value="Anguilla">Anguilla</option>&ndash;&gt;-->
                <!--&lt;!&ndash;</select>&ndash;&gt;-->
                    <!--{{form.country}}-->
                <!--</div>-->
              <!--</div>-->
              <div class="field-row">
                <!--<input type="text" name="email" placeholder="Your Email Id"  />-->
                  {{form.email}}
                   <span class="errors_email error"></span>
              </div>


              <div class="field-row you-are-here-to">
                  <h4>You are here to</h4>
                  <div class="you-are-here-row">
                    <div class="grid-50">
                    <label class="radio inline-cover">
                    <input type="radio" name="user_type" value="FREELANCER">

                    <span> I want to work </span>
                    </label>
                    </div>
                    <div class="grid-50">
                    <label class="radio inline-cover">
                    <input type="radio" name="user_type" value="CLIENT" >
                    <span> I want to hire</span>
                    </label>
                    </div>
                  </div>
                  <span class="errors_user_type error"></span>

              </div>

              <div class="field-row">
              <div class="grid-33 padding-right-5">
                  <!--<input type="button" class="light-blue-border-button" name="imageField" id="registration"  value="Sign Up" />-->

                  <button type="button" class="light-grey-border-button loading"  onclick="Registration()">Sign Up</button>
              </div>
              <div class="grid-33 padding-left-5">
                <button type="button" class="light-grey-border-button" onclick="ResetForm()">Cancel</button>
              </div>

              </div>

            </form>


             <p> You are already a member ? <a href="{% url 'index:login' %}" class="sign-up-link"> LOGIN </a> </p>

            </div>
      </div>
    </section>
    <!--register form ends here-->
<script>
    function ResetForm(){
        $('#registration')[0].reset();
        $('.error').hide();
    }
    function Registration(){
     $('.loading').addClass('has-loader has-input-loader');
     $('.loading').append('<div class="spinner-loader"></div><div class="loading-pulse-bg"></div>');

        $.ajax({
        url : "{% url 'index:register' %}", // the endpoint
        type : "POST", // http method
        data : $('#registration').serialize(), // data sent with the post request

        // handle a successful response
        success : function(data) {
           if(data.status=='failed'){
                $(".error").hide();
                $('.loading').removeClass('has-loader has-input-loader');
                $('.loading').html('Sign Up');

                $.each(data.data, function( index, value ) {
                   $(".errors_"+index).show();
                  $(".errors_"+index).html('<ul class="errorlist"><li>'+value+'</li></ul>');
                  console.log("#errors_"+index);

                  //$(".errors_"+index).delay(5500).fadeOut('slow');

                });

           }else{
             $("#success").show();
              $(".error").hide();
             $('.loading').removeClass('has-loader has-input-loader');
                $('.loading').html('Sign Up');

             //$("#success").html(data.message);
            // var text =data.message;

             // DisplayMessage('success',text);

             window.location.href="{% url 'index:registersuccess' %}";

             $('#registration')[0].reset();
             //$("#success").delay(5500).fadeOut('slow');
           }
        }
    });
    }
      function DisplayMessage(classs,text){
$(".status-message").removeClass('failed');
$(".status-message").removeClass('success');
$(".status-message").addClass(classs);
pos = $(".status-message").offset().top;
 $("html,body").animate({scrollTop:pos-300}, 1000);

$("#messageStatus").html(text);
$(".status-message").fadeIn('fast');
           setTimeout(function(){
             $(".status-message").fadeOut();
             //location.reload();



           }, 3000);
}
function HideDisplayMessage(){
 $(".status-message").fadeOut('fast');
}
</script>
{% endblock %}

templates/accounts/success_message.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block style %}

   <link rel="stylesheet" href="{% static 'css/create-profile.css' %}">
{% endblock %}
 {% block content %}
 <!--login form-->
    <section class="login-cover full-strip" id="login-cover">
      <div class="login-form-cover activation-message-cover">
	  <div class=" form-cover">
	  	  	<span class="succes-icon"></span>
			<h1>A verification email has been send to your email. Please check email</h1>
			<!--<a href="{% url 'index:login' %}" class="login-now">Login Now</a>-->
      </div>
	  </div>
    </section>
    <!--login form ends here-->
 {% endblock %}