client/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from client.views import ClientProfile, ClientJobPost, SerachFreelancer, PaginationView, FreelancerPaginationView, \
    MyJobs, JoblistPaginationView, JobDetails, JobInvitedPaginationView, FindJobs, EditJob

urlpatterns = [
    url(r'client-profile/$', login_required(ClientProfile.as_view()), name='clientprofile'),
    url(r'client-job-posting/$', login_required(ClientJobPost.as_view()), name='clientjobpost'),
    url(r'client-job-posting/(?P<slug>[-\w]+)/$', login_required(ClientJobPost.as_view()), name='clientjobpost'),
    url(r'edit-job/(?P<slug>[-\w]+)/$', login_required(EditJob.as_view()), name='editjobpost'),
    url(r'search-freelancer/$', login_required(SerachFreelancer.as_view()), name='searchfreelancer'),
    url(r'paginations-search/$', PaginationView.as_view(), name='paginationsearch'),
    url(r'jobs/$', MyJobs.as_view(), name='clientjobs'),

    url(r'find_jobs/$', FindJobs.as_view(), name='findjobs'),
    url(r'paginations-freelsearch/$', login_required(FreelancerPaginationView.as_view()), name='freelancerpagination'),
    url(r'paginations-jobss/$', JoblistPaginationView.as_view(), name='jobspagination'),
    url(r'paginations-jobsdetails/$', login_required(JobInvitedPaginationView.as_view()), name='jobdetails-pagination'),
    #url(r'freelancer-profile-view/$', login_required(FreelancerProfileView.as_view()), name='freelancerprofileview'),
    url(r'^client_job_details/(?P<slug>[-\w]+)/$', login_required(JobDetails.as_view()), name='jobdetails'),
]

freelancer/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from freelancer.views import FreelancerProfile, FreelancerProfileView, JobDetailsView, FreelancerJobList, \
    JoblistPaginations, FreelancerView

urlpatterns = [
    url(r'freelancer-profile/$', login_required(FreelancerProfile.as_view()), name='freelancerprofile'),
    url(r'freelancer-profile-view/$', login_required(FreelancerProfileView.as_view()), name='freelancerprofileview'),
    url(r'jobs-list/$', login_required(FreelancerJobList.as_view()), name='freelancerjoblist'),
    url(r'^freelancer_job_details/(?P<slug>[-\w]+)/$', login_required(JobDetailsView.as_view()), name='jobdetailsview'),
    url(r'paginations-jobs-freelancer/$', JoblistPaginations.as_view(), name='jobspaginationfreelancer'),
    url(r'profile_view/(?P<slug>[-\w]+)/$', FreelancerView.as_view(), name='profileview'),
]

hire/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from hire.views import HireView, FreelancerHireView, MilestoneListView

urlpatterns = [

    url(r'hire/(?P<slug>[-\w]+)/$', login_required(HireView.as_view()), name='hireviews'),
    url(r'hires/(?P<slug>[-\w]+)/$', login_required(FreelancerHireView.as_view()), name='hireviewsfreelancer'),
    url(r'listing-milestones$', login_required(MilestoneListView.as_view()), name='listmilestone'),

]

newproject/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin



import accounts
from newproject import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('accounts.urls')),
    url(r'^freelancer/', include('freelancer.urls')),
    url(r'^client/', include('client.urls')),
    url(r'^freelancer-company/', include('freelancer_company.urls')),
    url(r'^client-company/', include('client_company.urls')),
    url(r'^site_administration/', include('site_administration.urls',namespace='siteadmin')),

    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^hire/', include('hire.urls')),
    url(r'^notifications/', include('notifications.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += i18n_patterns(
    url(r'^', include('accounts.urls', namespace='index')),
    url(r'^polls/', include('accounts.urls', namespace='login')),
    url(r'^', include('freelancer.urls', namespace='freelancer')),
    url(r'^', include('client.urls', namespace='client')),
    url(r'^', include('hire.urls', namespace='hire')),
    url(r'^', include('freelancer_company.urls', namespace='freelancer-company')),
    url(r'^', include('client_company.urls', namespace='client-company')),
    url(r'^', include('notifications.urls', namespace='notifications')),
    url(r'^accounts/', include('registration.backends.hmac.urls'))
)

handler404 = accounts.views.error_404
handler500 = accounts.views.error_500

client/views.py
import base64
import datetime
import json

from django.core import serializers
from django.core.files.base import ContentFile
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.template.response import TemplateResponse
from django.urls import reverse
from django.views.generic import ListView
from django.views.generic import TemplateView
from rolepermissions.mixins import HasPermissionsMixin
from rolepermissions.roles import assign_role
from rolepermissions.roles import remove_role

# Create your views here.
from accounts.models import Users
from client.forms import ClientForm, PostJobForm, InviteForm
from client.mixins import ClientMixin
from client.models import Client_Profile, ClientJobs
from client_company.models import Client_Company_Profile

from freelancer.models import WorkCategories, Skills, WorkSubCategories
from hire.models import HiredJobsContract
from site_administration.models import VerificationJobPost
from threading import local

_thread_locals = local()


class ClientProfile(HasPermissionsMixin, ClientMixin, TemplateView):
    required_permission = 'View_Dashboard_Client'
    template_name = 'client/client-profile.html'

    def get(self, request):

        # all_jobs = self.get_my_jobs()

        template_name = 'client/client-profile.html'

        joblist = self.get_all_JobList()

        context = {'joblist': joblist.filter(user=request.user).order_by("-id")[:2]}
        return TemplateResponse(request, template_name, context)

    def post(self, request, *args, **kwargs):
        method = request.POST['method']
        if method == 'client_image_save':
            # print request.FILES['freelancer_image'],"cccccccccccccccccccccccccccccch"
            client_object, clientr_objects = Client_Profile.objects.get_or_create(user=request.user)
            if client_object:
                format, imgstr = request.POST['freelancer_image'].split(';base64,')
                ext = format.split('/')[-1]
                date_str = datetime.datetime.utcnow()
                data = ContentFile(base64.b64decode(imgstr), name=str(request.user.first_name) + date_str.strftime(
                    "%Y_%m_%d_%H_%M_%S_%f") + '.' + ext)
                client_object.profile = data
                client_object.save()
                option_html = render_to_string('client/ajax/client_profile_image.html',
                                               {'object': client_object.profile.url,
                                                'csrf_token_value': request.COOKIES['csrftoken'], request: request}
                                               )

            payload = {'status': 'sucess', 'message': "success", 'data': client_object.profile.url, 'html': option_html}
            return HttpResponse(json.dumps(payload),
                                content_type='application/json',
                                )
        if method == 'Save_User_Details':
            print "user"
            user = Users.objects.get(email=request.user)
            form = ClientForm(request.POST)
            if form.is_valid():
                user_object, user_objects = Users.objects.get_or_create(email=request.user)
                if user_object:
                    user_object.first_name = request.POST['first_name']
                    user_object.last_name = request.POST['last_name']
                    user_object.save()

                payload = {'status': 'success',
                           'message': 'Successfully Updated',
                           'data': 'g'}
                return HttpResponse(json.dumps(payload), content_type='application/json', )
            else:
                self.message = "Validation failed."
                self.data = form.errors
                self.success = False
                payload = {'status': 'failed', 'message': self.message, 'data': self.data}
                return HttpResponse(json.dumps(payload), content_type='application/json', )
        if method == 'Cancel_image':
            if request.POST['type'] == 'profile':
                try:
                    freelancer_object = Client_Profile.objects.get(user=request.user)
                    if freelancer_object.profile:
                        pic = freelancer_object.profile.url
                    else:
                        pic = ""
                except:
                    pic = ""

                option_html = render_to_string('client/ajax/client_profile_image.html',
                                               {'object': pic,
                                                'csrf_token_value': request.COOKIES['csrftoken'], request: request}
                                               )
                payload = {'status': 'sucess', 'message': "success",
                           'html': option_html}
                return HttpResponse(json.dumps(payload), content_type='application/json', )
            else:
                try:
                    freelancer_object = Client_Company_Profile.objects.get(
                        user=request.user.get_client_company_intance().user)
                    if freelancer_object.logo:
                        pic = freelancer_object.logo.url
                    else:
                        pic = ""
                except:
                    pic = ""
                option_html = render_to_string('client/ajax/client_company_logo.html',
                                               {'object': pic,
                                                'csrf_token_value': request.COOKIES['csrftoken'], request: request}
                                               )
                payload = {'status': 'sucess', 'message': "success",
                           'html': option_html}
                return HttpResponse(json.dumps(payload), content_type='application/json', )
        if method == 'Delete_image':
            if request.POST['type'] == 'profile':
                freelancer_object = Client_Profile.objects.get(user=request.user)
                freelancer_object.profile.delete()
                # freelancer_object.delete()

                option_html = render_to_string('client/ajax/client_profile_image.html',
                                               {'object': '',
                                                'csrf_token_value': request.COOKIES['csrftoken'], request: request}
                                               )
                payload = {'status': 'sucess', 'message': "success",
                           'html': option_html}
                return HttpResponse(json.dumps(payload), content_type='application/json', )
            if request.POST['type'] == 'logo':
                freelancer_object = Client_Company_Profile.objects.get(
                    user=request.user.get_client_company_intance().user)
                freelancer_object.logo.delete()
                # freelancer_object.delete()
                option_html = render_to_string('client/ajax/client_company_logo.html',
                                               {'object': '',
                                                'csrf_token_value': request.COOKIES['csrftoken'], request: request}
                                               )
                payload = {'status': 'sucess', 'message': "success",
                           'html': option_html}
                return HttpResponse(json.dumps(payload), content_type='application/json', )
        if method == 'get_worksubcategorys':

            # if len(request.POST.getlist('workid[]')) > 0:
            #     subid = self.get_sub_id(request.POST.getlist('workid[]'))
            # else:
            #     subid = self.get_sub_id(request.POST['workid'])
            if len(request.POST.getlist('workid[]')) > 0:
                subid = request.POST.getlist('workid[]')
            else:
                subid = [request.POST['workid']]

            leads_as_json = serializers.serialize('json', WorkSubCategories.objects.filter(
                work_category__in=subid))
            return HttpResponse(leads_as_json,
                                content_type='application/json',
                                )
        if method == 'get_workcategory':
            leads_as_json = serializers.serialize('json', WorkCategories.objects.all())
            return HttpResponse(leads_as_json,
                                content_type='application/json',
                                )
        if method == 'get_skillsoptions':
            # if len(request.POST.getlist('subid[]')) > 0:
            #     subid = self.get_sub_id(request.POST.getlist('subid[]'))
            # else:
            #     subid = self.get_sub_id(request.POST['subid'])
            if len(request.POST.getlist('subid[]')) > 0:
                subid = self.get_sub_id(request.POST.getlist('subid[]'))
            else:
                subid = [request.POST['subid']]

            getskills = Skills.objects.all()
            leads_as_json = serializers.serialize('json', Skills.objects.filter(
                category__in=subid))
            return HttpResponse(leads_as_json,
                                content_type='application/json',
                                )


class ClientJobPost(ClientMixin, TemplateView):
    template_name = 'client/client_job_posting.html'

    def get(self, request,**kwargs):

        # all_jobs = self.get_my_jobs()

        template_name = 'client/client_job_posting.html'
        Payment_type = self.get_all_Payment_type()
        job_status = self.get_all_job_status()
        duration = self.get_all_duration()
        get_previous_data = self.get_all_previous_data().order_by('-id')
        try:
            jobdetails = ClientJobs.objects.get(slug=kwargs.get('slug'))
        except:

            jobdetails =None

templates/client/ajax/client_company_logo.html
{% load static %}
<div class="image-editors profile-image-cover">

    {% if object %}
    <div class="cropit-preview profile-image" style="background: #eee url('{{object}}') repeat scroll 0 0; "><div class="loader company_loader_logo" style="display: none;"></div></div>
    {% else %}
    <div class="cropit-preview profile-image" style="background: #eee url('{% static 'images/company-logo.jpg' %}') repeat scroll 0 0; "><div class="loader company_loader_logo" style="display: none;"></div></div>

    {% endif %}

    <div class="crop-actions">
        <div class="cropit-image-zoom-input-cover">
            <input type="range" class="cropit-image-zoom-input">
        </div>
        <div class="profile-image-actions">
            <span class="upload-photo-link"><input type="file" class="cropit-image-input"></span> {% if object %}
            <span onclick="GetValues(this)" data-delete="logo" class="actions delete-photo">Delete Photo</span> {% else %}
            <span class="actions delete-photo">Delete Photo</span> {% endif %}
        </div>
        <div class="profile-image-actions secondary-actions">
        <span id="imageFields" class="actions save-photo">Save Photo</span>
            <span onclick="Cancel(this)" data-cancel="logo" class="actions cancel-photo">Cancel Photo</span>

        </div>
    </div>
    </div>
</div>

templates/client/ajax/client_profile_image.html
{% load static %}
<div class="image-editor profile-image-cover">

    {% if object %}
    <div class="cropit-preview profile-image" style="background: #eee url('{{object}}') no-repeat scroll 0 0; "><div class="loader loader_logo" style="display: none;"></div></div>
    {% else %}
    <div class="cropit-preview profile-image" style=" background: rgb(217, 227, 235) url('{% static 'images/no-image.svg'%}') no-repeat scroll center center / 182px auto;"><div class="loader loader_logo" style="display: none;"></div></div>

    {% endif %}
    <div class="crop-actions">
        <div class="cropit-image-zoom-input-cover">
            <input type="range" class="cropit-image-zoom-input">
        </div>
        <div class="profile-image-actions">
            <span class="upload-photo-link"><input type="file" class="cropit-image-input"></span> {% if object %}
            <span onclick="GetValues(this)" data-delete="profile" class="actions delete-photo">Delete Photo</span> {% else %}
            <span class="actions delete-photo">Delete Photo</span> {% endif %}
        </div>
        <div class="profile-image-actions secondary-actions">
            <span id="imageField" class="actions save-photo">Save Photo</span>
            <span onclick="Cancel(this)" data-cancel="profile" class="actions cancel-photo">Cancel Photo</span>

        </div>
    </div>
</div>

templates/client/ajax/job_invitedfreelancer_list.html
 {% load static %}
 {% load create_array %}

{% for invited in queryset%}
 {% if jobtype == 'Invitaion' %}

     <div class="freelancer-actions-list-row">
        <div class="freelancer-image grid-10">
        <div class="img-cover image-round">
       {% if invited.user.user.user_detail.get.profile %}
        <img src="{{invited.user.user.user_detail.get.profile.url}}" alt="">
        {% else %}
        <img src="{% static 'images/no-image.svg' %}" alt="">
            {% endif %}
            <div class="price-text">{% if invited.user.user.freelancer_hourly_user.get.hourly_rate %}{{invited.user.user.freelancer_hourly_user.get.hourly_rate}}{% endif %}</div>

        </div>
        </div>
        <div class="info-cover grid-90">
        <div class="grid-80">
        <h2>{{invited.user.user.first_name}} {{invited.user.user.last_name}}</h2>
        <p class="blue-text">{% if invited.user.user.freelancer_location_user.get.country.pk %}{{invited.user.user.freelancer_location_user.get.country.name}}{% endif %}  {% if invited.user.user.freelancer_location_user.get.state.pk %}| {{invited.user.user.freelancer_location_user.get.state.name}}{% endif %}  {% if invited.user.user.freelancer_location_user.get.city.pk %}| {{invited.user.user.freelancer_location_user.get.city.name}}{% endif %} </p>
        {% if invited.status.status == 'Cancelled' or invited.status.status == 'Declined' or invited.status.status == 'Withdrawn'  %}
           <div class="job-status rejected">{{invited.status.status}}</div>
        {% endif %}
        {% if invited.status.status == 'Accepted' %}
           <div class="job-status accepted">{{invited.status.status}}</div>
        {% endif %}
        </div>
        <div class="actions-cover grid-20">
        <a href="" class="cancel-button">Cancel</a>
        <a href="" class="reply">Reply</a>
        </div>
        <p class="more">
            {% if invited.user.user.user_detail.get.about %}{{invited.user.user.user_detail.get.about}}{% endif %}
        </p>
            {% if invited.status.status == 'Cancelled'  %}

         <span>Withdrawn by freelancer</span>
        {% endif %}
        {% if invited.status.status == 'Withdrawn'  %}

         <span>Withdrawn by client</span>
        {% endif %}
        {% if invited.status.status == 'Accepted'  %}

         <span>Invitation accepted by freelancer</span>
        {% endif %}
         </div>
     </div>
     {% elif jobtype == 'Applied' %}
        <div class="freelancer-actions-list-row">
        <div class="freelancer-image grid-10">
        <div class="img-cover image-round">
       {% if invited.user.user.user_detail.get.profile %}
        <img src="{{invited.user.user.user_detail.get.profile.url}}" alt="">
        {% else %}
        <img src="{% static 'images/no-image.svg' %}" alt="">
            {% endif %}
            <div class="price-text">{% if invited.estimated_cost %}${{invited.estimated_cost}}{% endif %}</div>
        </div>
        </div>
        <div class="info-cover grid-90">
        <div class="grid-80">
        <h2>{{invited.user.user.first_name}} {{invited.user.user.last_name}}</h2>
        <p class="blue-text">{% if invited.user.user.freelancer_location_user.get.country.pk %}{{invited.user.user.freelancer_location_user.get.country.name}}{% endif %}  {% if invited.user.user.freelancer_location_user.get.state.pk %}| {{invited.user.user.freelancer_location_user.get.state.name}}{% endif %}  {% if invited.user.user.freelancer_location_user.get.city.pk %}| {{invited.user.user.freelancer_location_user.get.city.name}}{% endif %} </p>
        {% if invited.status.status == 'Cancelled' or invited.status.status == 'Declined' or invited.status.status == 'Withdrawn'  %}
           <div class="job-status rejected">{{invited.status.status}}</div>
        {% endif %}
        </div>
        <div class="actions-cover grid-20">
        <a href="" class="cancel-button">Reply</a>
        {% if invited.status.status != 'Withdrawn' and invited.status.status != 'Cancelled' %}
            {% check_hired_or_not jobid invited.user as status %}
         {% if status == None %}
        <a class ="reply" onclick="GetHireDetails(this)"   data-freelancer="{{invited.user}}" class="reply">Hire</a>
        {% else %}
            <a class ="reply" href="{% url 'hire:hireviews' status.slug %}">Hired</a>
            {% endif %}
            {% endif %}
        </div>
        <p class="more">
            {% create_range page_obj as page_range %}
            {% if invited.status.status == 'Cancelled' and invited.cancel_message  %}
            {{invited.cancel_message}}
            {% else %}
            {{invited.description}}
            {% endif %}
            </p>

        {% if invited.status.status == 'Cancelled'  %}

         <span>Withdrawn by freelancer</span>
        {% endif %}
        {% if invited.status.status == 'Withdrawn'  %}

         <span>Withdrawn by client</span>
        {% endif %}
        </div>
        </div>
      {% elif jobtype == 'Hired' %}

     <div class="freelancer-actions-list-row">
        <div class="freelancer-image grid-10">
        <div class="img-cover image-round">

       {% if invited.freelancer_profile.profile %}
        <img src="{{invited.freelancer_profile.profile.url}}" alt="">
        {% else %}
        <img src="{% static 'images/no-image.svg' %}" alt="">
            {% endif %}
            <div class="price-text">{% if invited.budget %}${{invited.budget}}{% endif %}</div>
        </div>
        </div>
        <div class="info-cover grid-90">
        <div class="grid-80">
        <h2>{{invited.freelancer_profile.user.first_name}} {{invited.freelancer_profile.user.last_name}}</h2>
        <p class="blue-text">{% if freelancer_profile.user.freelancer_location_user.get.country.pk %}{{freelancer_profile.user.freelancer_location_user.get.country.name}}{% endif %}  {% if freelancer_profile.user.freelancer_location_user.get.state.pk %}| {{freelancer_profile.user.freelancer_location_user.get.state.name}}{% endif %}  {% if freelancer_profile.user.freelancer_location_user.get.city.pk %}| {{freelancer_profile.user.freelancer_location_user.get.city.name}}{% endif %} </p>
        {% if invited.status.status   %}
           <div class="job-status accepted">{{invited.status.status}}</div>
        {% endif %}
        </div>
        <div class="actions-cover grid-20">
        <a href="" class="cancel-button">Reply</a>

        <a  href="{% url 'hire:hireviews' invited.slug %}"  data-freelancer="{{invited.user}}" class="reply">Hired</a>

        </div>
        <p class="more">

            {% if invited.job_description  %}
            {{invited.job_description}}

            {% endif %}
            </p>


        </div>
        </div>

     {% endif %}
  {% empty %}
<div class="view-profile-single-section-nocontent">
  <p>No Content to show ..</p>
</div>
 {% endfor %}
 {% if page_obj.has_previous or  page_obj.has_next %}
 <div class="pagination-cover">
		<ul class="pagination">
         {% if page_obj.has_previous %}
        <li  data-attr="{{ page_obj.previous_page_number }}" data-method="Get_InvitedList" class="prev paginate_by"> <a>Prev</a></li>
        {% else %}
         <li class="visited"><a>Prev</a></li>
        {% endif %}


        <!--<li >-->
            <!--<a href="#" class="dropdown-toggle pagination-drop paginate_num" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">-->
                <!--{{ page_obj.number }}-->
            <!--</a>-->

                {% for page_number in page_obj.paginator.page_range %}
                                        <li class="paginate_by {% if page_obj.number == page_number %} Active {% elif  page_obj.number < page_number %} {% else %} visited  {% endif %} " data-method="Get_InvitedList"  data-attr="{{page_number}}"><a>0{{page_number}}</a></li>
                {% endfor %}

        <!--</li>-->
        {% if page_obj.has_next %}
        <li  data-attr="{{ page_obj.next_page_number }}" data-method="Get_InvitedList"  class="nex paginate_by"><a>Next</a> </li>
      {% else %}
        <li class="visited"><a>Next</a></li>
      {% endif %}

    </ul>
</div>
  {% endif %}

templates/client/ajax/job_list.html
 {% load static %}
 {% load create_array %}
<!--<section class="profile-introduction view-profile-single-section overview-cover" id="overview-cover" data-anchor="overview-cover">-->

        <!--<div class="my-post-jobs-cover load-content">-->
        <!--<div class="view-profile-single-section-header">-->
        <!--<div class="grid-100"><h2>My Jobs ({{count}})</h2></div>-->
            <!--<div class="list-search-cover">-->
			<!--<input placeholder="Find Freelancer :" type="text"><span class="search-button"> </span>-->

            <!--&lt;!&ndash;{% if request.user.is_authenticated %}&ndash;&gt;-->
         <!--&lt;!&ndash;{% ifequal request.user.active_account.type 'CLIENT'%}&ndash;&gt;-->
        <!--&lt;!&ndash;<div class="grid-50"><a href="{% url 'client:clientjobpost' %}" class="next-arrow-button pull-right">Post a New Job<i></i></a></div>&ndash;&gt;-->
        <!--&lt;!&ndash;{% endifequal %}&ndash;&gt;-->
            <!--&lt;!&ndash;{% endif %}&ndash;&gt;-->
        <!--</div>-->
        {% for job in queryset %}

        <div class="portfolio-single-cover post-job">
        <h3 class="sub-heading-arows job-heading">
               {% if request.user.is_authenticated %}
            {% ifequal request.user.active_account.type 'CLIENT'%}
       <a href="{% url 'client:jobdetails' job.slug %}">{{job.job_title}}</a>
         {% endifequal %}

        {% ifequal request.user.active_account.type 'FREELANCER'%}
       <a href="{% url 'freelancer:jobdetailsview' job.slug %}">{{job.job_title}}</a>
         {% endifequal %}
            {% else %}
            <a href="#">{{job.job_title}}</a>
            {% endif %}
        </h3>
        <p class="rate-info"> {% if job.payment_type.type %}{{job.payment_type.type}} {% if job.payment_type.id == 2 %}(${{job.budget}} ){% else %} ({% if job.hourly_min %}${{job.hourly_min}}{% else %}$0{%endif %} - {% if job.hourly_max %}${{job.hourly_max}}{% else %}$0{%endif %}){%endif %} -{%endif %}{{job.experiance_level}} {% if job.duration.date_range %}- Est. Time: {{job.duration.date_range}} {% endif %} {% if job.created_date %}- Posted: {{job.created_date}} {% endif %}</p>
        <p class="description more">
        {{job.job_description}}
        </p>
        <div class="skills-cover">
             {% for skils in job.job_skills.all %}

            <span class="skill {% if forloop.counter > 10 %} hide skillslist {% else%}ff{% endif %}">{{skils.name}}</span>
            {% endfor %}
            {% if job.job_skills.count > 10 %}
             <a  onclick="Moreskills(this)" class="more">more..</a>
             {% endif %}



        </div>
        <div class="jobs-post-link">
        <a href="" class="hired-freelancers underlined-link">Hired Freelancers <span>({{job.hire_jobs.count}})</span></a>
        <a href="" class="applied-freelancers underlined-link">Applied Freelancers <span>({{job.applied_jobs.count}})</span></a>
        {% if request.user.is_authenticated %}
          {% ifequal request.user.active_account.type 'CLIENT'%}
            <a href="{% url 'client:clientjobpost' job.slug %}"  class="repost-job bordered-link">Repost Job</a>
            <!--<a href="" class="active-job bordered-link">Active</a>-->
            <!--<a href="" class="deactive-job bordered-link">Deactive</a>-->
        {% endifequal %}
            {% endif %}
        </div>
        </div>
             {% empty %}
            <div class="view-profile-single-section-nocontent">
              <p>No Content to show ..</p>
            </div>
             {% endfor %}
<!--{% if page_obj.has_previous or  page_obj.has_next %}-->
            <!--<div class="pagination-cover">-->
		<!--<ul class="pagination">-->
         <!--{% if page_obj.has_previous %}-->
        <!--<li  data-attr="{{ page_obj.previous_page_number }}" data-method="Search_autocomplete" data-search="freelancer_search" class="prev paginate_by"> <a>Prev</a></li>-->
        <!--{% else %}-->
         <!--<li class="visited"><a>Prev</a></li>-->
        <!--{% endif %}-->


        <!--&lt;!&ndash;<li >&ndash;&gt;-->
            <!--&lt;!&ndash;<a href="#" class="dropdown-toggle pagination-drop paginate_num" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">&ndash;&gt;-->
                <!--&lt;!&ndash;{{ page_obj.number }}&ndash;&gt;-->
            <!--&lt;!&ndash;</a>&ndash;&gt;-->

               <!--{% create_range page_obj as page_range %}-->


                <!--{% for page_number in page_range %}-->

                                        <!--<li class="paginate_by {% if page_obj.number == page_number %} Active {% elif  page_obj.number < page_number %} {% else %} visited  {% endif %} " data-method="Search_autocomplete" data-search="freelancer_search" data-attr="{{page_number}}"><a>0{{page_number}}</a></li>-->

              <!--&lt;!&ndash;<li class="paginate_by  {% if  page_obj.number|add:'5' > page_number and page_obj.number <= page_number %}show{% else %}hide{% endif %} data-method="Search_autocomplete" data-search="freelancer_search" data-attr="{{page_number}}"><a>0{{page_number}}</a></li>&ndash;&gt;-->

               <!--{% endfor %}-->

        <!--&lt;!&ndash;</li>&ndash;&gt;-->
        <!--{% if page_obj.has_next %}-->
        <!--<li  data-attr="{{ page_obj.next_page_number }}" data-method="Search_autocomplete" data-search="freelancer_search" class="nex paginate_by"><a>Next</a> </li>-->
      <!--{% else %}-->
        <!--<li class="visited"><a>Next</a></li>-->
      <!--{% endif %}-->

    <!--</ul>-->
<!--</div>-->
 <!--{% endif %}-->
{% get_pagination 2 1 %}
        <!--</div>-->
        <!--</section>-->