client/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from client.views import ClientProfile, ClientJobPost, SerachFreelancer, PaginationView, FreelancerPaginationView, \
    MyJobs, JoblistPaginationView, JobDetails, JobInvitedPaginationView, FindJobs, EditJob

urlpatterns = [
    url(r'client-profile/$', login_required(ClientProfile.as_view()), name='clientprofile'),
    url(r'client-job-posting/$', login_required(ClientJobPost.as_view()), name='clientjobpost'),
    url(r'client-job-posting/(?P<slug>[-\w]+)/$', login_required(ClientJobPost.as_view()), name='clientjobpost'),
    url(r'edit-job/(?P<slug>[-\w]+)/$', login_required(EditJob.as_view()), name='editjobpost'),
    url(r'search-freelancer/$', login_required(SerachFreelancer.as_view()), name='searchfreelancer'),
    url(r'paginations-search/$', PaginationView.as_view(), name='paginationsearch'),
    url(r'jobs/$', MyJobs.as_view(), name='clientjobs'),

    url(r'find_jobs/$', FindJobs.as_view(), name='findjobs'),
    url(r'paginations-freelsearch/$', login_required(FreelancerPaginationView.as_view()), name='freelancerpagination'),
    url(r'paginations-jobss/$', JoblistPaginationView.as_view(), name='jobspagination'),
    url(r'paginations-jobsdetails/$', login_required(JobInvitedPaginationView.as_view()), name='jobdetails-pagination'),
    #url(r'freelancer-profile-view/$', login_required(FreelancerProfileView.as_view()), name='freelancerprofileview'),
    url(r'^client_job_details/(?P<slug>[-\w]+)/$', login_required(JobDetails.as_view()), name='jobdetails'),
]

client_company/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from client_company.views import ClientCompany, ClientCompanyView, InvitedUserList

urlpatterns = [
    url(r'client-company/$', login_required(ClientCompany.as_view()), name='clientcompany'),
    url(r'client-company-view/$', login_required(ClientCompanyView.as_view()), name='clientcompanyview'),
    url(r'client-pagination/$', login_required(InvitedUserList.as_view()), name='invitedlist'),
]

freelancer/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from freelancer.views import FreelancerProfile, FreelancerProfileView, JobDetailsView, FreelancerJobList, \
    JoblistPaginations, FreelancerView

urlpatterns = [
    url(r'freelancer-profile/$', login_required(FreelancerProfile.as_view()), name='freelancerprofile'),
    url(r'freelancer-profile-view/$', login_required(FreelancerProfileView.as_view()), name='freelancerprofileview'),
    url(r'jobs-list/$', login_required(FreelancerJobList.as_view()), name='freelancerjoblist'),
    url(r'^freelancer_job_details/(?P<slug>[-\w]+)/$', login_required(JobDetailsView.as_view()), name='jobdetailsview'),
    url(r'paginations-jobs-freelancer/$', JoblistPaginations.as_view(), name='jobspaginationfreelancer'),
    url(r'profile_view/(?P<slug>[-\w]+)/$', FreelancerView.as_view(), name='profileview'),
]

freelancer_company/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from freelancer_company.views import FreelancerCompany, FreelancerCompanyView, InvitedUserList

urlpatterns = [
    url(r'freelancer-company/$', login_required(FreelancerCompany.as_view()), name='freelancercompany'),
    url(r'freelancer-company-view/$', login_required(FreelancerCompanyView.as_view()), name='freelancercompanyview'),
    url(r'freelancer-pagination/$', login_required(InvitedUserList.as_view()), name='invitedlist'),
]

hire/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from hire.views import HireView, FreelancerHireView, MilestoneListView

urlpatterns = [

    url(r'hire/(?P<slug>[-\w]+)/$', login_required(HireView.as_view()), name='hireviews'),
    url(r'hires/(?P<slug>[-\w]+)/$', login_required(FreelancerHireView.as_view()), name='hireviewsfreelancer'),
    url(r'listing-milestones$', login_required(MilestoneListView.as_view()), name='listmilestone'),

]

newproject/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin



import accounts
from newproject import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('accounts.urls')),
    url(r'^freelancer/', include('freelancer.urls')),
    url(r'^client/', include('client.urls')),
    url(r'^freelancer-company/', include('freelancer_company.urls')),
    url(r'^client-company/', include('client_company.urls')),
    url(r'^site_administration/', include('site_administration.urls',namespace='siteadmin')),

    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^hire/', include('hire.urls')),
    url(r'^notifications/', include('notifications.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += i18n_patterns(
    url(r'^', include('accounts.urls', namespace='index')),
    url(r'^polls/', include('accounts.urls', namespace='login')),
    url(r'^', include('freelancer.urls', namespace='freelancer')),
    url(r'^', include('client.urls', namespace='client')),
    url(r'^', include('hire.urls', namespace='hire')),
    url(r'^', include('freelancer_company.urls', namespace='freelancer-company')),
    url(r'^', include('client_company.urls', namespace='client-company')),
    url(r'^', include('notifications.urls', namespace='notifications')),
    url(r'^accounts/', include('registration.backends.hmac.urls'))
)

handler404 = accounts.views.error_404
handler500 = accounts.views.error_500

notifications/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from notifications.views import NotificationCount, NotificationView, NotificationsListView

urlpatterns = [

    url(r'check-count$', login_required(NotificationCount.as_view()), name='checkcount'),
    url(r'notification$', login_required(NotificationView.as_view()), name='notificationview'),
    url(r'notification-list$', login_required(NotificationsListView.as_view()), name='notificationlist'),

]

notifications/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from accounts.models import BaseTimestamp, User_Type
from client.models import ClientJobs
from newproject import settings


class Notifications(BaseTimestamp):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='notification_user',
                             verbose_name="user")
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=500, blank=True, null=True)
    url = models.TextField(max_length=500, blank=True, null=True)
    job = models.ForeignKey(ClientJobs, blank=True, null=True)

    type = models.ForeignKey(User_Type,related_name='user_type_notification',null=True, blank=True,verbose_name="User Type")
    status = models.CharField(max_length=200)
    def __str__(self):
        return "{0}::{1}".format(self.user.first_name, self.title)

notifications/views.py
import json

from django.http import HttpResponse

# Create your views here.
from django.template.loader import render_to_string
from django.template.response import TemplateResponse
from django.views.generic import ListView
from django.views.generic import TemplateView

from accounts.models import Users, User_Type
from client.mixins import ClientMixin
from notifications.models import Notifications


class NotificationCount(ClientMixin,TemplateView):
    template_name = 'freelancer/freelancer_hire_view.html'

    def post(self, request, *args, **kwargs):
        if request.POST.get('method') == 'Check_count':
            notification =Notifications.objects.filter(user=request.user,status=0)
            #notification.status = 1
            notification.update(status=1)
            payload = {'status': 'success',
                       'type': '0', 'message': "Successfully", 'data': "k",
                     }
            return HttpResponse(json.dumps(payload), content_type='application/json')
        elif request.POST.get('method') == 'Save_notification':
            print request.POST.get('title')

            try:
                user = Users.objects.get(id=request.POST.get('user_id'))

            except:
                user = Users.objects.get(email=request.POST.get('user_id'))

            try:

                created_by = Users.objects.get(id=request.POST.get('created_by'))
            except:

                created_by = Users.objects.get(email=request.POST.get('created_by'))

            Notifications.objects.get_or_create(user=user, title=request.POST.get('title'), created_by=created_by, status=0,
                                                description=request.POST.get('description'),url=request.POST.get('url'),
                                                type=User_Type.objects.get(type=request.POST.get('type'),))

            payload = {'status': 'success',
                       'type': '0', 'message': "Successfully", 'data': "k",'classs':'contents_count'+request.POST.get('type')+request.POST.get('user_id')
                     }
            return HttpResponse(json.dumps(payload), content_type='application/json')
class NotificationView(ClientMixin,TemplateView):
    template_name = 'common/notification.html'
    def get(self, request,**kwargs):
        list =self.get_unread_notification(request.user.email,request.user.active_account).update(status=1)


        template_name = 'common/notification.html'
        notification = self.get_all_notification(request.user.email,request.user.active_account)



        context = {'notification': notification}
        return TemplateResponse(request, template_name, context)
class NotificationsListView(ClientMixin,ListView):
    paginate_by = 5

    def post(self, request, *args, **kwargs):
        response_data = {}
        if request.POST.get('method') == 'List_notifications':
            page_by = request.POST.get('page_by')
            list = self.get_all_notification(request.user.email,request.user.active_account).order_by('-id')
            paginator_response = self.get_paginated_notification_list(request, page_by, list)

            response_data['paginator_html'] = paginator_response['paginator_html']
            response_data['count'] = list.count()


            return HttpResponse(json.dumps(response_data), content_type="application/json")

    def get_paginated_notification_list(self,request, page_by, list):
        if page_by:
            page_by = int(page_by)
        else:
            page_by = 1


        page_size = self.get_paginate_by(list)
        size = self.paginate_queryset(list, page_size)
        paginator, page, queryset, is_paginated = size
        try:
            queryset = paginator.page(page_by).object_list
        except:
            queryset = queryset

        user_table = render_to_string('common/ajax/notification_list.html',
                                      {'queryset': queryset, 'paginator': paginator, 'page': page,
                                       'is_paginated': is_paginated, 'type': request.user.active_account,

                                       'page_obj': paginator.page(page_by)})

        # paginator_html = render_to_string('ajax/paginator_html.html',
        #                                   {'page_obj': paginator.page(page_by)})

        context = {'count': list.count(), 'paginator_html': user_table}
        return context

templates/common/Job_posting_edit_script.html
<script>
    $(document).ready(function() {
        getBudgetTextBox();
        ClosingDate();

        $(".work_category").each(function() {

            GetWorkcategory(this);
        });

});
function GetWorkcategory(elm) {

        $.ajax({
            url: "{% url 'client:clientprofile' %}", // the endpoint
            type: "POST", // http method
            data: {
                method: "get_workcategory",
                csrfmiddlewaretoken: '{{ csrf_token }}'
            }, // data sent with the post request

            // handle a successful response
            success: function(responses) {
                newOption = '<option value="" >Select Work Category</option>';

                $.map(responses, function(item) {
                    var select = '';
                    console.log($(elm).data('id'));
                    if ($(elm).data('id') != 0) {
                        if (item.pk == $(elm).data('id')) {
                            var select = 'selected="selected"';
                        } else {
                            var select = '';
                        }
                    }

                    newOption += '<option ' + select + ' value="' + item.pk + '">' + item.fields.category_title + '</option>';

                });

                $(elm).html(newOption);
                Getsubcategory(elm);
                GetSkills(elm);



            }
        });

    }

    function Getsubcategory(elm) {


        var workid = "0";
        if ($(elm).val() != '') {
            workid = $(elm).val()
        }

        $.ajax({
            url: "{% url 'client:clientprofile' %}", // the endpoint
            type: "POST", // http method
            data: {
                method: "get_worksubcategorys",
                csrfmiddlewaretoken: '{{ csrf_token }}',
                workid: workid
            }, // data sent with the post request

            // handle a successful response
            success: function(responses) {
                newOption = '<option value="0" >Select Sub Category</option>';
                if ($(elm).data('type') == '2') {
                    classs = 'clone-sec';
                } else {
                    classs = 'create-profile-form';
                }
                $.map(responses, function(item) {


                   if ($(elm).closest('.' + classs).find('.sub_category').data('id') != 0) {
                        if ($.inArray(item.pk, $(elm).closest('.' + classs).find('.sub_category').data('id')) > -1) {


                            var select = 'selected="selected"';
                        } else {
                            var select = '';
                        }
                    }


                    newOption += '<option ' + select + ' value="' + item.pk + '">' + item.fields.sub_category_title + '</option>';

                });

                $(elm).closest('.' + classs).find('.sub_category').html(newOption);
                $(elm).closest('.' + classs).find('.sub_category').select2();
                GetSkills(elm);




            }
        });


    }

    function GetSkills(elm) {

        var workid = "0";
        if ($(elm).val() != '') {
            workid = $(elm).val()
        }

        if ($(elm).data('type') == '2') {
            classs = 'clone-sec';
        } else {
            classs = 'create-profile-form';
        }
        $.ajax({
            url: "{% url 'client:clientprofile' %}", // the endpoint
            type: "POST", // http method
            data: {
                method: "get_skillsoptions",
                csrfmiddlewaretoken: '{{ csrf_token }}',
                subid: workid
            }, // data sent with the post request

            // handle a successful response
            success: function(responses) {
                newOption = '<option value="0" >Select skills</option>';
                if (responses) {
                    $.map(responses, function(item) {


 console.log($(elm).closest('.' + classs).find('.skillsoptions').data('id')+"gggggggggg");

                        if ($(elm).closest('.' + classs).find('.skillsoptions').data('id') != 0) {
                            if ($.inArray(item.pk, $(elm).closest('.' + classs).find('.skillsoptions').data('id')) > -1) {

                                var select = 'selected="selected"';
                            } else {
                                var select = '';
                            }
                        }

                        newOption += '<option ' + select + ' value="' + item.pk + '">' + item.fields.name + '</option>';

                    });
                }
                $(elm).closest('.' + classs).find('.skillsoptions').html(newOption);
                $(elm).closest('.' + classs).find('.skillsoptions').select2();

            }
        });

    }
     function getBudgetTextBox() {
        $(document).on('change', '#pay-type-selector', function() {
            $('.amount-type-fields').hide();
            $('.amount-type-fields').find('input[type=text]').attr('type', 'hidden');
            $('.amount-type-fields').find('input').attr('value', '');
            $('.amount-type-fields').addClass('hidefilds');

            $('.budget' + $(this).val()).show();
            $('.budget' + $(this).val()).find('input[type=hidden]').attr('type', 'text');
            $('.budget' + $(this).val()).find('input[type=hidden]').attr('value', '');
            $('.budget' + $(this).val()).removeClass('hidefilds');
        });
     }
     function ClosingDate() {
        $(".start-dates").datepicker({
            changeMonth: true,
            changeYear: true,
            minDate: new Date()
        });
    }



    function JobPost() {
        $(".body_loader").show();
        var cloneData = $("form#JobPosts input[type=text], form#JobPosts select");
        var values = {};
        cloneData.each(function(index, item) {


            if ($(this).val() == '' || $(this).val() == null) {
                values[this.name] = this.name;
                $('#' + $(this).data('classname')).removeClass('hide');
            } else {




                if (values[this.name]) {
                    values.slice($.inArray(this.name, JSON.stringify(values)), 1);
                }
                $('#' + $(this).data('classname')).addClass('hide');
            }
        });

        //alert(Object.keys(values).length);

        if (Object.keys(values).length == '0' || $('#errors_valid').val() == '1') {
            $('#errors_valid').val('1');
        } else {
            $('#errors_valid').val('0');
        }
        //alert($('#errors_valid').val());

        $.ajax({
            url: "{% url 'client:clientjobpost' %}", // the endpoint
            type: "POST", // http method
            data: $('#JobPosts').serialize(), // data sent with the post request

            // handle a successful response
            success: function(data) {
             $(".body_loader").hide();
                if (data.status == 'failed') {

                    $(".error").hide();

                   if(data.type == 0){
                    $.each(data.data, function(index, value) {
                        $(".errors_" + index).show();
                        if (value == 'Select a valid choice. That choice is not one of the available choices.') {
                            value = "Job Category is required";
                        }
                        $(".errors_" + index).html('<ul class="errorlist"><li>' + value + '</li></ul>');
                        console.log("#errors_" + index);


                        //$(".errors_"+index).delay(5500).fadeOut('slow');

                    });
                    pos = $(".errorlist").offset().top;
                     var anchor = $(".errorlist:first");
                     var position = anchor.position().top ;

                     $('html, body').animate({scrollTop:0},800);

                     $(".scroll-cover").animate({scrollTop:position}, 100);
                     }else{
                       var text = data.message;

                        localStorage.setItem('status_msg_company', 'true');
                        DisplayMessage('failed', text);
                     }

                } else {

                    $(".error").hide();

                    if (data.type == '1') {
                        var text = data.message;

                        localStorage.setItem('status_msg_company', 'true');
                        localStorage.setItem('status_msg_company_text', data.message);
                        //DisplayMessage('success', text);


                        $('#JobPosts')[0].reset();

                        //$("#job_details").val("0").change();
                        jobtitlechange();
                        window.location.href = "{% url 'client:clientjobs'%}";
                        var delay = 2000;
                        setTimeout(function(){  }, delay);

                    } else {
                        openPopup("small-dialog-error");

                    }


                }
            }
        });
    }
function Continue() {
        $('#errors_valid').val('1');
        Close();
        JobPost();
    }
</script>

templates/common/client_company_image.html
{% load staticfiles %}
<div class="profile-image-cover" >
   <div id="profile-images">
      <div class="image-editors profile-image-cover">
         {% if request.user.get_client_company_intance.logo %}
         <div class="cropit-preview profile-image" style="background: #eee url('{{request.user.get_client_company_intance.logo.url}}') no-repeat scroll 0 0; ">
            <div class="loader company_loader_logo" style="display: none;"></div>
         </div>
         {% else %}
         <div class="cropit-preview profile-image" style="background: #eee url('{% static 'images/company-logo.jpg' %}') no-repeat scroll 0 0; ">
            <div class="loader company_loader_logo" style="display: none;"></div>
         </div>
         {% endif %}
         <div class="crop-actions">
            <div class="cropit-image-zoom-input-cover">
               <input type="range" class="cropit-image-zoom-input">
            </div>
            <div class="profile-image-actions">
               <span class="upload-photo-link"><input type="file" class="cropit-image-input"></span>
               {% if request.user.get_client_company_intance.logo %}
               <span  onclick="GetValues(this)" data-delete="logo" class="actions delete-photo">Delete Photo</span>
               {% else %}
               <span  class=" actions delete-photo">Delete Photo</span>
               {% endif %}
            </div>
            <div class="profile-image-actions secondary-actions">
               <span id ="imageFields" class="actions save-photo">Save Photo</span>
               <span onclick="Cancel(this)" data-cancel="logo" class="actions cancel-photo">Cancel Photo</span>
            </div>
         </div>
      </div>
   </div>
</div>

templates/common/client_profile_script.html
<script>
 $(document).ready(function() {
 SaveClientPrfile();
 SaveCompanyLogo();
 });
function SaveClientPrfile() {
     $("#imageField").click(function() {
         var imageData = $('.image-editor').cropit('export');
         $(".loader_logo").show();
         $.ajax({
             url: "{% url 'client:clientprofile' %}", // the endpoint
             type: "POST", // http method
             data: {
                 method: "client_image_save",
                 freelancer_image: imageData,
                 csrfmiddlewaretoken: '{{ csrf_token }}'
             }, // data sent with the post request

             // handle a successful response
             success: function(data) {
             $(".loader_logo").hide();
                 if (data.status == 'failed') {

                 } else {
                     var path = data.data;
                     $("#profile-image").html(data.html);
                     $('.image-editor').cropit();
                     SaveClientPrfile();



                 }
             }
         });
     });

 }

 function SaveCompanyLogo() {
     $("#imageFields").click(function() {
      $(".company_loader_logo").show();
         var imageData = $('.image-editors').cropit('export');
         $.ajax({
             url: "{% url 'client-company:clientcompany' %}", // the endpoint
             type: "POST", // http method
             data: {
                 method: "client_company_image_save",
                 freelancer_image: imageData,
                 csrfmiddlewaretoken: '{{ csrf_token }}'
             }, // data sent with the post request

             // handle a successful response
             success: function(data) {
              $(".company_loader_logo").hide();
                 if (data.status == 'failed') {

                 } else {
                     var path = data.data;


                     $("#profile-images").html(data.html);
                     $('.image-editors').cropit();
                     SaveCompanyLogo();

                 }
             }
         });
     });

 }
 function Cancel(elm) {


     $.ajax({
         url: "{% url 'client:clientprofile' %}", // the endpoint
         type: "POST", // http method
         data: {
             method: 'Cancel_image',
             type: $(elm).data('cancel'),
             csrfmiddlewaretoken: '{{ csrf_token }}'
         }, // data sent with the post request

         // handle a successful response
         success: function(data) {
             if (data.status == 'failed') {
                 $(".error").hide();


             } else {

                 if ($(elm).data('cancel') == 'profile') {
                     $("#profile-image").html(data.html);
                     $('.image-editor').cropit();
                     SaveClientPrfile();
                 } else {
                     $("#profile-images").html(data.html);
                     $('.image-editors').cropit();
                     SaveCompanyLogo();
                 }




             }
         }
     });

 }

 function Delete() {
     $.ajax({
         url: "{% url 'client:clientprofile' %}", // the endpoint
         type: "POST", // http method
         data: {
             method: 'Delete_image',
             type: $("#typeimage").val(),
             csrfmiddlewaretoken: '{{ csrf_token }}'
         }, // data sent with the post request

         // handle a successful response
         success: function(data) {
             if (data.status == 'failed') {
                 $(".error").hide();


             } else {

                 $.magnificPopup.close();

                 if ($("#typeimage").val() == 'profile') {
                     $("#profile-image").html(data.html);
                     $('.image-editor').cropit();
                     SaveClientPrfile();
                 } else {
                     $("#profile-images").html(data.html);
                     $('.image-editors').cropit();
                     SaveCompanyLogo();
                 }




             }
         }
     });


 }

 function GetValues(elm) {
     var title = $(elm).data("delete");
     $('#typeimage').val(title);
     $.magnificPopup.open({
         items: {
             src: '#small-dialog_delete_image'
         }
     });

 }

</script>

templates/common/freelancer_profile_script.html
<script>
$(document).ready(function() {
SaveFreelancerProfileImage();
SaveFreelancerCompanyLogo();
});
function Cancel(elm) {
   var loader = $(elm).data('loader');
        $("." + loader).show();
    $.ajax({
        url: "{% url 'freelancer:freelancerprofileview' %}", // the endpoint
        type: "POST", // http method
        data: {
            method: 'Cancel_image',
            type: $(elm).data('cancel'),
            csrfmiddlewaretoken: '{{ csrf_token }}'
        }, // data sent with the post request

        // handle a successful response
        success: function(data) {
            $(".loader_logo").hide();
            if (data.status == 'failed') {
                $(".error").hide();


            } else {

                if ($(elm).data('cancel') == 'profile') {
                        $("#profile-image").html(data.html);
                        $('.image-editor').cropit();
                        SaveFreelancerProfileImage();
                    } else {
                        $("#profile-images").html(data.html);

                        $('.image-editors').cropit();
                        SaveFreelancerCompanyLogo();
                    }






            }
        }
    });

}

function Delete() {

    $.ajax({
        url: "{% url 'freelancer:freelancerprofileview' %}", // the endpoint
        type: "POST", // http method
        data: {
            method: 'Delete_image',
            type: $("#typeimage").val(),
            csrfmiddlewaretoken: '{{ csrf_token }}'
        }, // data sent with the post request

        // handle a successful response
        success: function(data) {
            if (data.status == 'failed') {
                $(".error").hide();


            } else {

                $.magnificPopup.close();
                if ($("#typeimage").val() == 'profile') {
                        $("#profile-image").html(data.html);

                        $('.image-editor').cropit();
                        SaveFreelancerProfileImage();
                    } else {
                        $("#profile-images").html(data.html);
                        $('.image-editors').cropit();
                        SaveFreelancerCompanyLogo();
                    }





            }
        }
    });


}

function GetValues(elm) {
    var title = $(elm).data("delete");
    $('#typeimage').val(title);
    $.magnificPopup.open({
        items: {
            src: '#small-dialog_delete_image'
        }
    });

}
function SaveFreelancerProfileImage() {
    $("#imageField").click(function() {
        var imageData = $('.image-editor').cropit('export');
        $(".loader_logo").show();
        $.ajax({
            url: "{% url 'freelancer:freelancerprofile' %}", // the endpoint
            type: "POST", // http method
            data: {
                method: "freelancer_image_save",
                freelancer_image: imageData,
                csrfmiddlewaretoken: '{{ csrf_token }}'
            }, // data sent with the post request

            // handle a successful response
            success: function(data) {
                $(".loader_logo").hide();
                if (data.status == 'failed') {

                } else {
                    var path = data.data;


                    $("#profile-image").html(data.html);
                    $('.image-editor').cropit();
                    SaveFreelancerProfileImage();

                }
            }
        });
    });
}
function SaveFreelancerCompanyLogo() {
        $("#imageFields").click(function() {
            var imageData = $('.image-editors').cropit('export');
            $(".company_loader_logo").show();
            $.ajax({
                url: "{% url 'freelancer-company:freelancercompany' %}", // the endpoint
                type: "POST", // http method
                data: {
                    method: "freelancer_company_image_save",
                    company_image: imageData,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                }, // data sent with the post request

                // handle a successful response
                success: function(data) {
                    $(".company_loader_logo").show();
                    if (data.status == 'failed') {

                    } else {
                        var path = data.data;


                        $("#profile-images").html(data.html);
                        $('.image-editors').cropit();
                        SaveFreelancerCompanyLogo();
                    }
                }
            });
        });
    }
</script>

templates/common/loader.html
<div class="loader body_loader">
</div>

templates/common/message.html
<div class="status-message ">
     <p id="messageStatus">Success Message will goes here </p>
     <a href="#" onclick="HideDisplayMessage()" class="close"></a>
</div>