accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
# from django.contrib.auth import views as auth_views

from accounts import views
from accounts.views import Home, Registers, Dashboard, logout, CompanyActivate, Activated, SuccessMessage, \
    ResetPasswordRequestView, PasswordResetConfirmView

urlpatterns = [
    url(r'^test/$', views.index, name='home'),
    url(r'^$', Home.as_view(), name='home'),
    url(r'register/$', Registers.as_view(), name='register'),
    url(r'activate/$', Activated.as_view(), name='activateaccount'),
    url(r'companyactivate/(?P<token>[\w-]+)$', CompanyActivate.as_view(), name='companyactivate'),
    url(r'clientdashboard/$', login_required(Dashboard.as_view()), name='dashboard'),
    url(r'registration-success/$', SuccessMessage.as_view(), name='registersuccess'),
    url(r'signin/$', views.login, name='login'),
    url(r'^logout/$', logout, {"next_page": '/'}, name="logout"),
    url(r'^reset_password', ResetPasswordRequestView.as_view(), name="reset_password"),
    url(r'^account/reset_password_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(),
        name='confirmpaass'),

    # url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    # url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    # url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #     auth_views.password_reset_confirm, name='password_reset_confirm'),
    # url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    # url(r'^accounts/activate/(?P<activation_key>\w+)/$',
    #     Home.as_view(),
    #     {'backend': 'registration.backends.default.DefaultBackend'},
    #     name='registration_activate'),
]

client/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from client.views import ClientProfile, ClientJobPost, SerachFreelancer, PaginationView, FreelancerPaginationView, \
    MyJobs, JoblistPaginationView, JobDetails, JobInvitedPaginationView, FindJobs, EditJob

urlpatterns = [
    url(r'client-profile/$', login_required(ClientProfile.as_view()), name='clientprofile'),
    url(r'client-job-posting/$', login_required(ClientJobPost.as_view()), name='clientjobpost'),
    url(r'client-job-posting/(?P<slug>[-\w]+)/$', login_required(ClientJobPost.as_view()), name='clientjobpost'),
    url(r'edit-job/(?P<slug>[-\w]+)/$', login_required(EditJob.as_view()), name='editjobpost'),
    url(r'search-freelancer/$', login_required(SerachFreelancer.as_view()), name='searchfreelancer'),
    url(r'paginations-search/$', PaginationView.as_view(), name='paginationsearch'),
    url(r'jobs/$', MyJobs.as_view(), name='clientjobs'),

    url(r'find_jobs/$', FindJobs.as_view(), name='findjobs'),
    url(r'paginations-freelsearch/$', login_required(FreelancerPaginationView.as_view()), name='freelancerpagination'),
    url(r'paginations-jobss/$', JoblistPaginationView.as_view(), name='jobspagination'),
    url(r'paginations-jobsdetails/$', login_required(JobInvitedPaginationView.as_view()), name='jobdetails-pagination'),
    #url(r'freelancer-profile-view/$', login_required(FreelancerProfileView.as_view()), name='freelancerprofileview'),
    url(r'^client_job_details/(?P<slug>[-\w]+)/$', login_required(JobDetails.as_view()), name='jobdetails'),
]

freelancer/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from freelancer.views import FreelancerProfile, FreelancerProfileView, JobDetailsView, FreelancerJobList, \
    JoblistPaginations, FreelancerView

urlpatterns = [
    url(r'freelancer-profile/$', login_required(FreelancerProfile.as_view()), name='freelancerprofile'),
    url(r'freelancer-profile-view/$', login_required(FreelancerProfileView.as_view()), name='freelancerprofileview'),
    url(r'jobs-list/$', login_required(FreelancerJobList.as_view()), name='freelancerjoblist'),
    url(r'^freelancer_job_details/(?P<slug>[-\w]+)/$', login_required(JobDetailsView.as_view()), name='jobdetailsview'),
    url(r'paginations-jobs-freelancer/$', JoblistPaginations.as_view(), name='jobspaginationfreelancer'),
    url(r'profile_view/(?P<slug>[-\w]+)/$', FreelancerView.as_view(), name='profileview'),
]

hire/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from hire.views import HireView, FreelancerHireView, MilestoneListView

urlpatterns = [

    url(r'hire/(?P<slug>[-\w]+)/$', login_required(HireView.as_view()), name='hireviews'),
    url(r'hires/(?P<slug>[-\w]+)/$', login_required(FreelancerHireView.as_view()), name='hireviewsfreelancer'),
    url(r'listing-milestones$', login_required(MilestoneListView.as_view()), name='listmilestone'),

]

newproject/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin



import accounts
from newproject import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('accounts.urls')),
    url(r'^freelancer/', include('freelancer.urls')),
    url(r'^client/', include('client.urls')),
    url(r'^freelancer-company/', include('freelancer_company.urls')),
    url(r'^client-company/', include('client_company.urls')),
    url(r'^site_administration/', include('site_administration.urls',namespace='siteadmin')),

    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^hire/', include('hire.urls')),
    url(r'^notifications/', include('notifications.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += i18n_patterns(
    url(r'^', include('accounts.urls', namespace='index')),
    url(r'^polls/', include('accounts.urls', namespace='login')),
    url(r'^', include('freelancer.urls', namespace='freelancer')),
    url(r'^', include('client.urls', namespace='client')),
    url(r'^', include('hire.urls', namespace='hire')),
    url(r'^', include('freelancer_company.urls', namespace='freelancer-company')),
    url(r'^', include('client_company.urls', namespace='client-company')),
    url(r'^', include('notifications.urls', namespace='notifications')),
    url(r'^accounts/', include('registration.backends.hmac.urls'))
)

handler404 = accounts.views.error_404
handler500 = accounts.views.error_500

notifications/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from notifications.views import NotificationCount, NotificationView, NotificationsListView

urlpatterns = [

    url(r'check-count$', login_required(NotificationCount.as_view()), name='checkcount'),
    url(r'notification$', login_required(NotificationView.as_view()), name='notificationview'),
    url(r'notification-list$', login_required(NotificationsListView.as_view()), name='notificationlist'),

]

templates/admin_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load static %}
    <title> {% block title %} Atlancer {% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'admin/vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'admin/vendors/font-awesome/css/font-awesome.min.css'  %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'admin/vendors/nprogress/nprogress.css' %}" rel="stylesheet">
    <!-- Animate.css -->
    <link href="{% static 'admin/vendors/animate.css/animate.min.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'admin/build/css/custom.min.css' %}" rel="stylesheet">
     <link href="{% static 'admin/vendors/iCheck/skins/flat/green.css' %}" rel="stylesheet">
	<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

    {% block style %}
    {% endblock %}
    {% block extra_js %}
    {% endblock %}
  </head>
<body class="nav-md">

<div class="container body">
      <div class="main_container">
          <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="{% url 'index:home' %}" class="site_title"><i class="fa fa-paw"></i> <span>Atlancer</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile">
              <div class="profile_pic">
                <img src="{% static 'admin/images/user.png' %}" alt="..." class="img-circle profile_img">
              </div>
              <div class="profile_info">
                <span>Welcome,</span>
                <h2>{{request.user.first_name}}</h2>
              </div>
            </div>
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              {% if request.user.is_superuser %}
              <div class="menu_section" >
                <h3>General</h3>
                <ul class="nav side-menu">
                  <li><a href="{% url 'siteadmin:AdmincreateList' %}"><i class="fa fa-home"></i> Role List </a>

                  </li>
                </ul>
              </div>
              {% endif %}
              <div class="menu_section">
                {% if request.user.is_superuser %}
                {% else %}
                <h3>General</h3>
                {% endif %}
                <ul class="nav side-menu">
                  <li><a href="{% url 'siteadmin:AdminClientList' %}"><i class="fa fa-bug"></i> Client List<!--span class="fa fa-chevron-down"></span--></a></li>
                  <li><a href="{% url 'siteadmin:AdminFreelancerList' %}"><i class="fa fa-bug"></i> Freelancer List<!--span class="fa fa-chevron-down"></span--></a></li>
                  <!--<li><a><i class="fa fa-sitemap"></i> Main Menu 3 <span class="fa fa-chevron-down"></span></a>-->
                    <!--<ul class="nav child_menu">-->
                        <!--<li><a>Level One<span class="fa fa-chevron-down"></span></a>-->
                                               <!--</li>-->
                        <!--</li>-->
                    <!--</ul>-->
                  </li>
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->

            <!-- /menu footer buttons -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="{% static 'admin/images/user.png' %}" alt="">{{request.user.first_name}}
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">

                    <li><a href="{% url 'siteadmin:adminlogout' %}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                  </ul>
                </li>


              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->
        <!-- page content -->
          {% block content %}

          {% endblock %}
        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Atlancer Admin <a href="">atlancer.com</a>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>
 <!-- jQuery -->

    <script src="{% static 'admin/vendors/jquery/dist/jquery.min.js' %}"></script>

    <!-- Bootstrap -->
    <script src="{% static 'admin/vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'admin/vendors/fastclick/lib/fastclick.js' %}"></script>
    <!-- NProgress -->
    <script src="{% static 'admin/vendors/nprogress/nprogress.js' %}"></script>
    <!-- iCheck -->
    <script src="{% static 'admin/vendors/iCheck/icheck.min.js' %}"></script>



    <!-- Custom Theme Scripts -->
    <script src="{% static 'admin/build/js/custom.min.js' %}"></script>

</body>
</html>

templates/client_header.html
{% load static %}
{% load create_array %}
<ul class="nav navbar-nav navbar-right header-element">

                   <li>
                     <a href="{% url 'client:searchfreelancer' %}">Find Freelancer </a>
                   </li><li>
                     <a href="{% url 'client:clientjobs' %}">My Jobs</a>
                   </li>

                   <li>
                     <a href="{% url 'client:clientjobpost' %}">Post jobs</a>
                   </li>
                   <li>
                         <!--{% Get_notification request.user.id as notification %}-->
                        <!--<a href="{% url 'notifications:notificationview' %}" class="notification-link notification_click" data-id="contents_count{{request.user.active_account}}{{request.user.id}}">-->
                            <!--<span class="{% if notification %} notification-count {% endif %} contents_count{{request.user.active_account}}{{request.user.id}}">{% if notification %}{{notification.count}}{% endif %}</span>-->
                        <!--</a>-->
                         {% Get_notification request.user.id as notification %}
                        <a  href="{% url 'notifications:notificationview' %}" class="notification-link notification_click" data-id="contents_count{{request.user.active_account}}{{request.user.id}}">
                            <span class="{% if notification %}notification-count{% endif %} contents_count{{request.user.active_account}}{{request.user.id}}">{% if notification %}{% if notification.count > 50 %}2+{% else %}{{notification.count}}{% endif %}{% endif %}</span>
                        </a>
                   </li>
                 </ul>

templates/freelancer_header.html
{% load static %}
{% load create_array %}
<ul class="nav navbar-nav navbar-right header-element">

                   <li>
                     <a href="{% url 'client:clientjobs' %}">Find Jobs</a>
                   </li><li>
                     <a href="{% url 'freelancer:freelancerjoblist' %}">My Jobs</a>
                   </li>
                    <li>
                         {% Get_notification request.user.id as notification %}
                        <a  href="{% url 'notifications:notificationview' %}" class="notification-link notification_click" data-id="contents_count{{request.user.active_account}}{{request.user.id}}">
                            <span class="{% if notification %}notification-count{% endif %} contents_count{{request.user.active_account}}{{request.user.id}}">{% if notification %}{% if notification.count > 50 %}2+{% else %}{{notification.count}}{% endif %}{% endif %}</span>
                        </a>
                   </li>



                 </ul>